### ISSUE TITLE
Análisis

### ISSUE THREAD

**Issue by jpadilla** [TheIndexingProject/contratospr-api#16]
Idealmente tenemos una sección donde mostramos un análisis de la data disponible.

```
- Trends
  - Date range - Presets: PR Fiscal Year(July 1st - June 30th)
  - $$$
  - # Contratos
  - # Contratistas
  - Average $ per contract

- Contracts
  - Biggest and smallest contracts
  - Trends

- Service groups / Service
  - Biggest and smallest contracts
  - Trends

- Contractor
  - Biggest and smallest contracts
  - Trends
```

Attached example UI from Stripe

<img width="782" alt="screen shot 2018-11-26 at 10 33 58 pm" src="https://user-images.githubusercontent.com/83319/49056874-6b8f2b00-f1cb-11e8-8cd9-ff106fa070f0.png">

**Comment by froi** [comment]
Para empezar voy a explorar la data y ver que queries tendríamos que hacer.

**Comment by ian-flores** [comment]
Hola, tengo un poco de experiencia haciendo visualizaciones.  Me gustaría colaborar con el proyecto, habría algún lenguaje en especifico en el que implementar las visualizaciones? O si puedo ayudar en otra parte del proyecto, me pueden dejar saber.

**Comment by jpadilla** [comment]
@ian-flores hey, gracias por ofrecer tu ayuda! Definitivamente hay oportunidad de colaborar aquí. Creo que como siguiente paso, @froi debería tener una mejor idea de lo que podemos hacer partiendo de nuestra última conversación.

@ian-flores En adición a esto, mira a ver si algún otro issue marcado con [good first issue](https://github.com/TheIndexingProject/tracking-contratos-pr/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) o [help wanted](https://github.com/TheIndexingProject/tracking-contratos-pr/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) te interesa. ✨

**Comment by froi** [comment]
Una idea para el UI de las tendencias:

![trends-template](https://user-images.githubusercontent.com/1918027/50543347-21231480-0ba4-11e9-8aca-1c0a403c582f.jpg)

Estoy buscando una manera "sencilla" de mostrar data relevante sin abrumar al usuario.

Any thoughts? @jpadilla @ian-flores

**Comment by froi** [comment]
Initial pass at some sort of UI for trends:

<img width="1920" alt="trends-initial-ui" src="https://user-images.githubusercontent.com/1918027/50546099-0d9d9b00-0bf0-11e9-9675-b26505d780db.png">
