### ISSUE TITLE
Contratos Impugnados

### ISSUE THREAD

**Issue by abdyelg** [TheIndexingProject/contratospr-api#35]
Esto es mas bien un posible feature que pueden añadir. Seria bueno tener visibilidad cual contrato esta siendo impugnado y una posible busqueda con contratistas que tengan contratos impugnados. 

Puedes ser desplegado con algun marcador en el contrato. Y en la lista de contratistas algun count de los contratos impugnados.

**Comment by froi** [comment]
Estaremos verificando la data disponible de https://consultacontratos.ocpr.gov.pr/ para ver si se pueden identificar.

**Comment by froi** [comment]
De lo que he visto la data no especifica si el contrato esta impugnado. Tampoco veo una manera de solicitar esa data directamente al contralor mediante la pagina.

Estaria excelente si le hacemos una solicitud "oficial" para que le añadan esa data.

Voy a cerrar el issue ya que no podemos hacer algo del lado nuestro. Si te animas a enviar una peticicion para añadir esa data y te contestan puedes reabrir este mismo issue con la respuesta que te den.
