### ISSUE TITLE
Contratos otorgados por año fiscal

### ISSUE THREAD

**Issue by jpadilla** [TheIndexingProject/contratospr-api#44]
Just noticed a new feature on https://consultacontratos.ocpr.gov.pr

<img width="1322" alt="Screen Shot 2019-05-12 at 2 05 54 PM" src="https://user-images.githubusercontent.com/83319/57586127-2df33580-74bf-11e9-96d5-b21ca4a20caa.png">

Here's a snippet of the CSV downloaded for 2018-2019.

```
Número de Entidad | Entidad | Número de Contrato | Enmienda | Otorgado En | Vigencia Desde | Vigencia Hasta | Tipo de Servicio | Categoría de Servicio | Cancelado | Cuantía | Contratista
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
4070 | Municipio de Toa Baja | 1994-000264 | AM | 05-01-2019 | 05-01-2019 | 05-01-2020 | VIVIENDAS | COMPRA, VENTA Y/O ALQUILER DE INMUEBLES |   | 9132 | NELSON OQUENDO DIAZ
4040 | Municipio de Juncos | 1996-000042 | R | 07-19-2018 | 08-01-2018 | 07-31-2019 | VIVIENDAS | COMPRA, VENTA Y/O ALQUILER DE INMUEBLES |   | 4596 | ISMAEL ALEJANDRO GUTIERREZ
4048 | Municipio de Maricao | 1997-000040 | V | 10-31-2018 | 10-31-2018 | 10-31-2019 | VIVIENDAS | COMPRA, VENTA Y/O ALQUILER DE INMUEBLES |   | 3720 | JARIL HOLDINGS CO. INC.
4070 | Municipio de Toa Baja | 1997-000208 | BN | 08-01-2018 | 08-01-2018 | 08-01-2019 | VIVIENDAS | COMPRA, VENTA Y/O ALQUILER DE INMUEBLES |   | 3912 | GILBERTO RAMOS VERA
4070 | Municipio de Toa Baja | 1997-000208 | BO | 09-01-2018 | 09-01-2018 | 09-01-2019 | VIVIENDAS | COMPRA, VENTA Y/O ALQUILER DE INMUEBLES |   | 5184 | GILBERTO RAMOS VERA
4070 | Municipio de Toa Baja | 1997-000215 | AA | 09-24-2018 | 10-01-2018 | 10-01-2019 | VIVIENDAS | COMPRA, VENTA Y/O ALQUILER DE INMUEBLES |   | 5676 | CARLOS D. AYALA
4070 | Municipio de Toa Baja | 1997-000310 | V | 10-01-2018 | 10-01-2018 | 10-01-2019 | VIVIENDAS | COMPRA, VENTA Y/O ALQUILER DE INMUEBLES |   | 4740 | ANGEL A. AVILES
```

Maybe we can use this to our advantage somehow 🤔

**Comment by froi** [comment]
Creo que ahi esta la data para hacer trends y visualizaciones.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by froi** [comment]
Mirando esto un poco mas creo que se puede hacer un processo de ETL que lo tome, limpie la data y haga una proceso de eliminacion de duplicados.

No se puede usar algunos de los textos para comparacion ya que el sistema de donde viene no trabaja bien con acentos. Por ejemplo algunos nombres de entidades estan errorneas, se tendria que usar el `numero de entidad` para encontrar la entidad correcta.

Tambien existen discrepancias con las fechas de los contratos. Algunas son enmiendas que fueron otorgadas despues de la fecha de vigencia. No se cuan correcto sea esto.

**Comment by froi** [comment]
Example mappings:

| Contralor Data | Our Models |
| --------------- | ----------- |
Numero de Entidad | Entity.source_id
Entidad | Entity.name
Número de Contrato | Contract.number
Enmienda | Contract.amendment
Otorgado En | Contract.date_of_grant
Contratista | Contractor.name

**Comment by froi** [comment]
Otra idea. ¿Qué pasaria si sometemos esta data al instituto de estadisticas, https://data.pr.gov?

**Comment by froi** [comment]
Volví a mirar esto. El problema mas grande que veo es que no manejan unicode bien en la exportación de data. El UI de la pagina del contralor lo meneja bien.

No creo que debamos de intentar de arreglar data de export que ellos sueltan.

Closing this out.
