### ISSUE TITLE
Project setup fails using backup.dump file

### ISSUE THREAD

**Issue by froi** [TheIndexingProject/contratospr-api#91]
**Describe the bug**

The `backup.dump` file that we are including in our setup instructions is causing the Django migrations to fail. The main reason is that the sequences for some tables are not being exported correctly.

I noticed this when I was trying to run migrations and would get an `null constraint` error. Checking the `django_migrations` table I saw the sequence was missing.

**To Reproduce**

1. Follow the setup steps, it'll fail when trying to run the migrations.

**Expected behavior**
Migrations should be applied without an error.

**Screenshots**

Error can be seen here https://github.com/TheIndexingProject/contratospr-api/pull/86#issuecomment-546641444

**Additional context**

I think the best way to solve this for future contributors / users is to not have the `backup.dump` and export the data using the `manage.py dumpdata` command. The resulting file can then be used after all migrations have been made. This way we let the framework do it's job.

**Comment by froi** [comment]
This should block PR #86 

Once this is resolved we can merge the changes into the `add-setup` branch and proceed with the PR.

**Comment by jpadilla** [comment]
Best to create a new dump from production. That last migration was created after the dump was made. I'll do this.

**Comment by jpadilla** [comment]
@froi try this one instead.

https://s3.amazonaws.com/data.contratospr.com/2019-10-27/backup.dump

**Comment by froi** [comment]
What options are you using for the dump? I also made a new dump and had the same error.

**Comment by jpadilla** [comment]
@froi `pg_dump -Fc --no-acl --no-owner -h HOSTNAME -p PORT -U USERNAME contratospr-api > docker/postgres/backup.dump`

**Comment by froi** [comment]
I’ll import it and make sure that the sequences are there. Thanks!

**Comment by froi** [comment]
To clarify, the error was never about the data. It was all about what was included in the export. I think we’re better off letting Django do it’s thing and have some test data that people can import.

**Comment by froi** [comment]
The issue was with the volumes and images that docker/docker-compose had already made. Since the images and volumes where already there and the `init.sh` script for the postgres container/image was being ignored. This would prevent the correct `backup.dump` file to be imported and would in turn cause the sequences in the DB to never exist and make our migrations fail.

The answer to solve this is to wipe everything related to the `docker-compose` images and resources. To accomplish this we can just run `docker-compose down --rmi all -v --remove-orphans`.

This is solved and unblocks #86 .
